@EcoFleet.API_HostAddress = https://localhost:7205/api/v1/vehicles

# @timeout 120000
GET {{EcoFleet.API_HostAddress}}?Page=1&RecordsByPage=10&Id=10056BCF-2843-4EF7-9A5D-CF750E6FD06B&Status=1&Plate=2222-7777&latitude=0&longitude=0&CurrentDriverId=10056BCF-2843-4EF7-9A5D-CF750E6FD06B

###

# @timeout 120000
GET {{EcoFleet.API_HostAddress}}/10056BCF-2843-4EF7-9A5D-CF750E6FD06A

###

# @timeout 120000
POST {{EcoFleet.API_HostAddress}}
Content-Type: application/json


{
    "LicensePlate" : "333-222",
    "Latitude" : 40.416,
    "Longitude" : -3.703,
    "CurrentDriverId" : "D290F1EE-6C54-4B01-90E6-D701748F0851"
}

###

# @timeout 120000
PUT {{EcoFleet.API_HostAddress}}/1A309A1B-C058-4DA2-A7FC-FA64D2A92E51
Content-Type: application/json


  {
    "Id": "1A309A1B-C058-4DA2-A7FC-FA64D2A92E51",
    "LicensePlate" : "2222-7777",
    "Latitude" : 7,
    "Longitude" : 7,
    "CurrentDriverId" : "10056BCF-2843-4EF7-9A5D-CF750E6FD06B"
}

###

# @timeout 120000
PATCH {{EcoFleet.API_HostAddress}}/maintenance/F7936BAB-6CCD-47F2-86A1-13374AF5C51F
Content-Type: application/json

###


# @timeout 120000
DELETE {{EcoFleet.API_HostAddress}}/1A309A1B-C058-4DA2-A7FC-FA64D2A92E51
Content-Type: application/json

###

# Response
